name       : perl-gtk3
version    : '0.038'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/Gtk3-0.038.tar.gz : 70dc4bf2aa74981c79e15fd298d998e05a92eba4811f1ad5c9f1f4de37737acc
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Perl interface to the 3.x series of the gtk+ toolkit
description: |
    Perl bindings to the 3.x series of the gtk+ toolkit.  This module allows you to write graphical user interfaces in a Perlish and object-oriented way, freeing you from the casting and memory management in C, yet remaining very close in spirit to original API.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - perl-glib-object-introspection
    - perl-cairo-gobject
rundeps    :
    - perl-glib-object-introspection
    - perl-cairo-gobject
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
